frontend:
  replicaCount: 1
  image:
    repository: danhvm12345/chatbot-frontend
    tag: "sha256:ffc53519f1140cbcd6c1e23a88b2ae4c565555c83cd5f58d4746d067637b055f"
    pullPolicy: Always
  containerPort: 3000
  servicePort: 3000
  serviceName: chatbot-frontend-svc
backend:
  replicaCount: 2
  image:
    repository: danhvm12345/chatbot-backend
    tag: "sha256:040089e59a3e19dea91fd90224c1e7c4ddc8215bce0893009b87f6ef41383d59"
    pullPolicy: Always
  containerPort: 8000
  servicePort: 8000
  serviceName: chatbot-backend-svc
  backendApiPath: "/chat"
ingress:
  host: chatbot.danhvuive.34.121.113.166.nip.io