frontend:
  replicaCount: 1
  image:
    repository: danhvm12345/chatbot-frontend
    tag: "latest"
    pullPolicy: Always
  containerPort: 3000
  servicePort: 3000
  serviceName: chatbot-frontend-svc
backend:
  replicaCount: 2
  image:
    repository: danhvm12345/chatbot-backend
    tag: "latest"
    pullPolicy: Always
  containerPort: 8000
  servicePort: 8000
  serviceName: chatbot-backend-svc
  backendApiPath: "/chat"
ingress:
  host: chatbot.danhvuive.34.121.113.166.nip.io