frontend:
  replicaCount: 1
  image:
    repository: danhvm12345/chatbot-frontend
    tag: "sha256:c98df0cb426520ec7b487e16e178b725934b89886f0f6d2c6278c172346707e5"
    pullPolicy: Always
  containerPort: 3000
  servicePort: 3000
  serviceName: chatbot-frontend-svc
backend:
  replicaCount: 2
  image:
    repository: danhvm12345/chatbot-backend
    tag: "sha256:c0eea4d739371898b4aa83d94f4b877bbc451ee8b719d4939857a9dc6ae7151d"
    pullPolicy: Always
  containerPort: 8000
  servicePort: 8000
  serviceName: chatbot-backend-svc
  backendApiPath: "/chat"
ingress:
  host: chatbot.danhvuive.34.121.113.166.nip.io