frontend:
  replicaCount: 1
  image:
    repository: danhvm12345/chatbot-frontend
    tag: "sha256:77c602950eee97b0b799093c60beb2ce8c658012e6c69e9940512787b4aba250"
    pullPolicy: Always
  containerPort: 3000
  servicePort: 3000
  serviceName: chatbot-frontend-svc
backend:
  replicaCount: 2
  image:
    repository: danhvm12345/chatbot-backend
    tag: "sha256:bdbe0808d962044da5b9d3af0de6f75a2094f57acbdfa2af2dc81f56baee9c86"
    pullPolicy: Always
  containerPort: 8000
  servicePort: 8000
  serviceName: chatbot-backend-svc
  backendApiPath: "/chat"
ingress:
  host: chatbot.danhvuive.34.121.113.166.nip.io