apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.backend.serviceName }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer 
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}