apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer 
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}