apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: model-serving
  # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#controller_summary
  annotations:
    kubernetes.io/ingress.class: "nginx" # which can be replaced by gce, gce-internal or istio
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"    # Connection timeout in seconds
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"      # Send timeout in seconds
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"      # Read timeout in seconds
    # nginx.ingress.kubernetes.io/proxy-body-size: "8m"          # Client request body size
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "600"
    nginx.ingress.kubernetes.io/keep-alive: "600"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.frontend.servicePort }}
      - path: /openapi.json
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.frontend.servicePort }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.serviceName }}
            port:
              number: {{ .Values.frontend.servicePort }}
              
      - path: /chat
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.serviceName }}
            port:
              number: {{ .Values.backend.servicePort }}
