apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: model-serving
  # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#controller_summary
  annotations:
    kubernetes.io/ingress.class: "nginx" # which can be replaced by gce, gce-internal or istio
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.frontend.servicePort }}
      - path: /openapi.json
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.frontend.servicePort }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.serviceName }}
            port:
              number: {{ .Values.frontend.servicePort }}
              
      - path: /chat
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.serviceName }}
            port:
              number: {{ .Values.backend.servicePort }}
